// Latest
export const VIEW_LATEST_ANIME = 'VIEW_LATEST_ANIME'
export const VIEW_LATEST_ANIME_REQUEST = 'VIEW_LATEST_ANIME_REQUEST'
export const VIEW_LATEST_ANIME_COMPLETED = 'VIEW_LATEST_ANIME_COMPLETED'
export const VIEW_LATEST_ANIME_ERROR = 'VIEW_LATEST_ANIME_ERROR'
export const RESET_VIEW_LATEST_ANIME = 'RESET_VIEW_LATEST_ANIME'

// Popular
export const VIEW_POPULAR_ANIME = 'VIEW_POPULAR_ANIME'
export const VIEW_POPULAR_ANIME_REQUEST = 'VIEW_POPULAR_ANIME_REQUEST'
export const VIEW_POPULAR_ANIME_COMPLETED = 'VIEW_POPULAR_ANIME_COMPLETED'
export const VIEW_POPULAR_ANIME_ERROR = 'VIEW_POPULAR_ANIME_ERROR'
export const RESET_VIEW_POPULAR_ANIME = 'RESET_VIEW_POPULAR_ANIME'

// Info
export const VIEW_INFO_ANIME = 'VIEW_INFO_ANIME'
export const VIEW_INFO_ANIME_REQUEST = 'VIEW_INFO_ANIME_REQUEST'
export const VIEW_INFO_ANIME_COMPLETED = 'VIEW_INFO_ANIME_COMPLETED'
export const VIEW_INFO_ANIME_ERROR = 'VIEW_INFO_ANIME_ERROR'
export const RESET_VIEW_INFO_ANIME = 'RESET_VIEW_INFO_ANIME'

// Watch
export const WATCH_ANIME = 'WATCH_ANIME'
export const WATCH_ANIME_REQUEST = 'WATCH_ANIME_REQUEST'
export const WATCH_ANIME_COMPLETED = 'WATCH_ANIME_COMPLETED'
export const WATCH_ANIME_ERROR = 'WATCH_ANIME_ERROR'
export const RESET_WATCH_ANIME = 'RESET_WATCH_ANIME'
